<a href="https://colab.research.google.com/github/sri-spirited/fchollet-book-deep-learning-with-python-notebooks/blob/master/2.3.Tensor_Operations.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Element-wise operations

## `relu` operation
The `relu` operation is an _element-wise_ operation, i.e. applied independently to each entry in the tensor. It is therefore amenable to massively parallel (_vectorized_) implementations

### Naive implementation of an element-wise relu operation:

In [10]:
import numpy as np
def naive_relu(x):
  #First check that it is a 2-D tensor
  assert len(x.shape)==2

  x = x.copy()#Avoid overwriting the inut 
  for i in range(x.shape[0]):
    for j in range(x.shape[1]):
      x[i,j] = max(x[i,j], 0)
  return x

Let's check the `naive_relu` function on x.

In [11]:
x = np.array([[5, -78, 2, 34, 0],
              [6, 79, 3, -35, 1],
              [7, 80, 4, 36, 2]])
x.ndim

2

In [12]:
naive_relu(x)

array([[ 5,  0,  2, 34,  0],
       [ 6, 79,  3,  0,  1],
       [ 7, 80,  4, 36,  2]])

We see that the negative elements have been replaced by 0

### Naive implementation of addition operation

In [14]:
def naive_add(x, y):
  assert len(x.shape)==2
  assert x.shape==y.shape

  x = x.copy()
  for i in range(x.shape[0]):
    for j in range(x.shape[1]):
      x[i, j] += y[i, j]
  return x

In [16]:
x = np.array([[5, -78, 2, 34, 0],
              [6, 79, 3, -35, 1],
              [7, 80, 4, 36, 2]])
y = np.ones(shape=(3,5))
print(x, "\n", y, "\n", "x+y: \n", naive_add(x,y))

[[  5 -78   2  34   0]
 [  6  79   3 -35   1]
 [  7  80   4  36   2]] 
 [[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]] 
 x+y: 
 [[  6 -77   3  35   1]
 [  7  80   4 -34   2]
 [  8  81   5  37   3]]


### `relu`in `numpy`

In [24]:
x = np.array([[5, -78, 2, 34, 0],
              [6, 79, 3, -35, 1],
              [7, 80, 4, 36, 2]])

np.maximum(x, np.zeros(shape = x.shape))

array([[ 5.,  0.,  2., 34.,  0.],
       [ 6., 79.,  3.,  0.,  1.],
       [ 7., 80.,  4., 36.,  2.]])

## Tensor broadcasting
What happens with addition when the shapes of the two tensors
being added differ?

When possible, and if there’s no ambiguity, the smaller tensor will be broadcasted to match the shape of the larger tensor. Broadcasting consists of two steps:
1. Axes (called broadcast axes) are added to the smaller tensor to match the ndim of the larger tensor.
2. The smaller tensor is repeated alongside these new axes to match the full shape of the larger tensor.

In [25]:
def naive_add_matrix_and_vector(x, y):
  assert len(x.shape)==2
  assert len(y.shape)==1
  assert x.shape[1]==y.shape[0]
  
  x = x.copy()
  for i in range(x.shape[0]):
    for j in range(x.shape[1]):
      x[i, j] += y[j]
  return x

In [26]:
x = np.array([[5, -78, 2, 34, 0],
              [6, 79, 3, -35, 1],
              [7, 80, 4, 36, 2]])
y = np.ones(shape=(x.shape[1],))
naive_add_matrix_and_vector(x, y)

array([[  6, -77,   3,  35,   1],
       [  7,  80,   4, -34,   2],
       [  8,  81,   5,  37,   3]])

## Tensor dot product 

In [27]:
import numpy as np
np.dot(x, y)

array([-37.,  54., 129.])

Let's break down the dot product for vectors

In [29]:
def naive_vector_dot(x,y):
  assert len(x.shape)==1
  assert len(y.shape)==1
  assert x.shape[0]==y.shape[0]
  z=0
  for i in range(x.shape[0]):
    z += x[i]*y[i]
  return z

Dot product for a matrix and a vector

In [39]:
def naive_matrix_vector_dot(x,y):
  assert len(x.shape)==2
  assert len(y.shape)==1
  assert x.shape[1]==y.shape[0]
  z = np.zeros(shape=(x.shape[0]))
  print(z)
  for i in range(x.shape[0]):
    print(f"i={i}")
    for j in range(x.shape[1]):
      print(f"j={j}")
      z[i] += x[i,j]*y[j]
  return z
x = np.array([[5, -78, 2, 34, 0],
              [6, 79, 3, -35, 1],
              [7, 80, 4, 36, 2]])
print(f"Shape of x: {x.shape} \n shape of y: {y.shape}")
y = np.ones(shape=x.shape[1])
naive_matrix_vector_dot(x,y)

Shape of x: (3, 5) 
 shape of y: (5,)
[0. 0. 0.]
i=0
j=0
j=1
j=2
j=3
j=4
i=1
j=0
j=1
j=2
j=3
j=4
i=2
j=0
j=1
j=2
j=3
j=4


array([-37.,  54., 129.])

In [37]:
range(x.shape[0])

range(0, 3)